-- Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.
module Monk.Runtime.Abi2 (abiVersion, abiProfile, abiCapabilities, abiTargets, abiOperationName, abiOpcodes) where

abiVersion :: Int
abiVersion = 2

abiProfile :: String
abiProfile = "bash53-i64"

abiCapabilities :: String
abiCapabilities = "argv bytes-platform child-capture child-run descriptor-state directory echo exec-site expansion glob integer launch pattern pattern-parts pipe-paths printf session split write-builtin"

abiTargets :: [String]
abiTargets = ["x86_64-linux", "aarch64-linux", "aarch64-darwin"]

abiOperationName :: String -> Maybe String
abiOperationName "NativeArgv" = Just "argv"
abiOperationName "NativePlatformBytes" = Just "bytes-platform"
abiOperationName "NativeChildCapture" = Just "child-capture"
abiOperationName "NativeChildRun" = Just "child-run"
abiOperationName "NativeDescriptorState" = Just "descriptor-state"
abiOperationName "NativeDirectory" = Just "directory"
abiOperationName "NativeEcho" = Just "echo"
abiOperationName "NativeExec" = Just "exec-site"
abiOperationName "NativeExpansion" = Just "expansion"
abiOperationName "NativeGlob" = Just "glob"
abiOperationName "NativeInteger" = Just "integer"
abiOperationName "NativeLaunch" = Just "launch"
abiOperationName "NativePattern" = Just "pattern"
abiOperationName "NativePatternParts" = Just "pattern-parts"
abiOperationName "NativePipePaths" = Just "pipe-paths"
abiOperationName "NativeSession" = Just "session"
abiOperationName "NativeSplit" = Just "split"
abiOperationName "NativeWrite" = Just "write-builtin"
abiOperationName _ = Nothing

abiOpcodes :: [(String, String)]
abiOpcodes =
  [ ("cli", "argv"),
    ("cli", "bytes-platform"),
    ("cli", "child-capture"),
    ("cli", "child-capture-session"),
    ("cli", "child-run"),
    ("cli", "child-run-session"),
    ("cli", "descriptor-state"),
    ("cli", "directory-diagnostic"),
    ("cli", "directory-initial-oldpwd"),
    ("cli", "directory-path-bound"),
    ("cli", "directory-physical"),
    ("cli", "directory-stack"),
    ("cli", "directory-validate"),
    ("cli", "echo"),
    ("cli", "exec-site"),
    ("cli", "expansion"),
    ("cli", "glob"),
    ("cli", "integer"),
    ("cli", "launch"),
    ("cli", "pattern"),
    ("cli", "pattern-parts"),
    ("cli", "pipe-paths"),
    ("cli", "printf"),
    ("cli", "raise-signal"),
    ("cli", "session-client"),
    ("cli", "session-directory-diagnostic"),
    ("cli", "session-exec-error"),
    ("cli", "session-guardian"),
    ("cli", "session-prepare"),
    ("cli", "session-run"),
    ("cli", "session-write"),
    ("cli", "split"),
    ("cli", "write-builtin"),
    ("session", "capture"),
    ("session", "fd-close"),
    ("session", "fd-data"),
    ("session", "fd-dup"),
    ("session", "fd-endpoint"),
    ("session", "fd-open"),
    ("session", "fd-pop"),
    ("session", "fd-push"),
    ("session", "fd-reset"),
    ("session", "finish-signal"),
    ("session", "ping"),
    ("session", "read"),
    ("session", "run"),
    ("session", "spawn"),
    ("session", "substitution"),
    ("session", "substitution-release"),
    ("session", "wait"),
    ("integer", "add"),
    ("integer", "and"),
    ("integer", "batch"),
    ("integer", "div"),
    ("integer", "eq"),
    ("integer", "ge"),
    ("integer", "gt"),
    ("integer", "invert"),
    ("integer", "le"),
    ("integer", "logical-and"),
    ("integer", "logical-or"),
    ("integer", "lt"),
    ("integer", "mul"),
    ("integer", "ne"),
    ("integer", "neg"),
    ("integer", "not"),
    ("integer", "or"),
    ("integer", "pos"),
    ("integer", "pow"),
    ("integer", "push"),
    ("integer", "read"),
    ("integer", "rem"),
    ("integer", "shl"),
    ("integer", "shr"),
    ("integer", "sub"),
    ("integer", "xor"),
    ("pattern", "match"),
    ("pattern", "replace-all"),
    ("pattern", "replace-first"),
    ("pattern", "trim-prefix-long"),
    ("pattern", "trim-prefix-short"),
    ("pattern", "trim-suffix-long"),
    ("pattern", "trim-suffix-short"),
    ("body", "body"),
    ("body", "builtin"),
    ("body", "directory-output"),
    ("body", "external"),
    ("body", "external-site"),
    ("body", "pipeline"),
    ("body", "snapshot")
  ]
