-- Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.
module Monk.Runtime.Abi2 (abiVersion, abiProfile, abiCapabilities, abiTargets, NativeOperation (..), abiOperationName, abiOpcodes, CliOpcode (..), cliOpcodeName, SessionOpcode (..), sessionOpcodeName, IntegerOpcode (..), integerOpcodeName, PatternOpcode (..), patternOpcodeName, BodyOpcode (..), bodyOpcodeName) where

abiVersion :: Int
abiVersion = 2

abiProfile :: String
abiProfile = "bash53-i64"

abiCapabilities :: String
abiCapabilities = "argv bytes-platform child-capture child-run descriptor-state directory echo exec-site expansion glob integer launch pattern pattern-parts pipe-paths printf session split write-builtin"

abiTargets :: [String]
abiTargets = ["x86_64-linux", "aarch64-linux", "aarch64-darwin"]

data NativeOperation
  = NativeInteger
  | NativeSplit
  | NativeArgv
  | NativeEcho
  | NativePattern
  | NativePatternParts
  | NativePlatformBytes
  | NativeGlob
  | NativeChildRun
  | NativeChildCapture
  | NativeDescriptorState
  | NativeDirectory
  | NativeSession
  | NativeExec
  | NativeWrite
  | NativeLaunch
  | NativeExpansion
  | NativePipePaths
  deriving stock (Show, Eq, Ord, Enum, Bounded)

abiOperationName :: NativeOperation -> String
abiOperationName NativeInteger = "integer"
abiOperationName NativeSplit = "split"
abiOperationName NativeArgv = "argv"
abiOperationName NativeEcho = "echo"
abiOperationName NativePattern = "pattern"
abiOperationName NativePatternParts = "pattern-parts"
abiOperationName NativePlatformBytes = "bytes-platform"
abiOperationName NativeGlob = "glob"
abiOperationName NativeChildRun = "child-run"
abiOperationName NativeChildCapture = "child-capture"
abiOperationName NativeDescriptorState = "descriptor-state"
abiOperationName NativeDirectory = "directory"
abiOperationName NativeSession = "session"
abiOperationName NativeExec = "exec-site"
abiOperationName NativeWrite = "write-builtin"
abiOperationName NativeLaunch = "launch"
abiOperationName NativeExpansion = "expansion"
abiOperationName NativePipePaths = "pipe-paths"

abiOpcodes :: [(String, String)]
abiOpcodes =
  [ ("cli", "argv"),
    ("cli", "bytes-platform"),
    ("cli", "child-capture"),
    ("cli", "child-capture-session"),
    ("cli", "child-run"),
    ("cli", "child-run-session"),
    ("cli", "descriptor-state"),
    ("cli", "directory-diagnostic"),
    ("cli", "directory-initial-oldpwd"),
    ("cli", "directory-path-bound"),
    ("cli", "directory-physical"),
    ("cli", "directory-stack"),
    ("cli", "directory-validate"),
    ("cli", "echo"),
    ("cli", "exec-site"),
    ("cli", "expansion"),
    ("cli", "glob"),
    ("cli", "integer"),
    ("cli", "launch"),
    ("cli", "pattern"),
    ("cli", "pattern-parts"),
    ("cli", "pipe-paths"),
    ("cli", "printf"),
    ("cli", "raise-signal"),
    ("cli", "session-client"),
    ("cli", "session-directory-diagnostic"),
    ("cli", "session-exec-error"),
    ("cli", "session-guardian"),
    ("cli", "session-prepare"),
    ("cli", "session-run"),
    ("cli", "session-write"),
    ("cli", "split"),
    ("cli", "write-builtin"),
    ("session", "capture"),
    ("session", "fd-close"),
    ("session", "fd-data"),
    ("session", "fd-dup"),
    ("session", "fd-endpoint"),
    ("session", "fd-open"),
    ("session", "fd-pop"),
    ("session", "fd-push"),
    ("session", "fd-reset"),
    ("session", "finish-signal"),
    ("session", "ping"),
    ("session", "read"),
    ("session", "run"),
    ("session", "spawn"),
    ("session", "substitution"),
    ("session", "substitution-release"),
    ("session", "wait"),
    ("integer", "add"),
    ("integer", "and"),
    ("integer", "batch"),
    ("integer", "div"),
    ("integer", "eq"),
    ("integer", "ge"),
    ("integer", "gt"),
    ("integer", "invert"),
    ("integer", "le"),
    ("integer", "logical-and"),
    ("integer", "logical-or"),
    ("integer", "lt"),
    ("integer", "mul"),
    ("integer", "ne"),
    ("integer", "neg"),
    ("integer", "not"),
    ("integer", "or"),
    ("integer", "pos"),
    ("integer", "pow"),
    ("integer", "push"),
    ("integer", "read"),
    ("integer", "rem"),
    ("integer", "shl"),
    ("integer", "shr"),
    ("integer", "sub"),
    ("integer", "xor"),
    ("pattern", "match"),
    ("pattern", "replace-all"),
    ("pattern", "replace-first"),
    ("pattern", "trim-prefix-long"),
    ("pattern", "trim-prefix-short"),
    ("pattern", "trim-suffix-long"),
    ("pattern", "trim-suffix-short"),
    ("body", "body"),
    ("body", "builtin"),
    ("body", "directory-output"),
    ("body", "external"),
    ("body", "external-site"),
    ("body", "pipeline"),
    ("body", "snapshot")
  ]

data CliOpcode
  = CliArgv
  | CliBytesPlatform
  | CliChildCapture
  | CliChildCaptureSession
  | CliChildRun
  | CliChildRunSession
  | CliDescriptorState
  | CliDirectoryDiagnostic
  | CliDirectoryInitialOldpwd
  | CliDirectoryPathBound
  | CliDirectoryPhysical
  | CliDirectoryStack
  | CliDirectoryValidate
  | CliEcho
  | CliExecSite
  | CliExpansion
  | CliGlob
  | CliInteger
  | CliLaunch
  | CliPattern
  | CliPatternParts
  | CliPipePaths
  | CliPrintf
  | CliRaiseSignal
  | CliSessionClient
  | CliSessionDirectoryDiagnostic
  | CliSessionExecError
  | CliSessionGuardian
  | CliSessionPrepare
  | CliSessionRun
  | CliSessionWrite
  | CliSplit
  | CliWriteBuiltin
  deriving stock (Show, Eq, Ord, Enum, Bounded)

cliOpcodeName :: CliOpcode -> String
cliOpcodeName CliArgv = "argv"
cliOpcodeName CliBytesPlatform = "bytes-platform"
cliOpcodeName CliChildCapture = "child-capture"
cliOpcodeName CliChildCaptureSession = "child-capture-session"
cliOpcodeName CliChildRun = "child-run"
cliOpcodeName CliChildRunSession = "child-run-session"
cliOpcodeName CliDescriptorState = "descriptor-state"
cliOpcodeName CliDirectoryDiagnostic = "directory-diagnostic"
cliOpcodeName CliDirectoryInitialOldpwd = "directory-initial-oldpwd"
cliOpcodeName CliDirectoryPathBound = "directory-path-bound"
cliOpcodeName CliDirectoryPhysical = "directory-physical"
cliOpcodeName CliDirectoryStack = "directory-stack"
cliOpcodeName CliDirectoryValidate = "directory-validate"
cliOpcodeName CliEcho = "echo"
cliOpcodeName CliExecSite = "exec-site"
cliOpcodeName CliExpansion = "expansion"
cliOpcodeName CliGlob = "glob"
cliOpcodeName CliInteger = "integer"
cliOpcodeName CliLaunch = "launch"
cliOpcodeName CliPattern = "pattern"
cliOpcodeName CliPatternParts = "pattern-parts"
cliOpcodeName CliPipePaths = "pipe-paths"
cliOpcodeName CliPrintf = "printf"
cliOpcodeName CliRaiseSignal = "raise-signal"
cliOpcodeName CliSessionClient = "session-client"
cliOpcodeName CliSessionDirectoryDiagnostic = "session-directory-diagnostic"
cliOpcodeName CliSessionExecError = "session-exec-error"
cliOpcodeName CliSessionGuardian = "session-guardian"
cliOpcodeName CliSessionPrepare = "session-prepare"
cliOpcodeName CliSessionRun = "session-run"
cliOpcodeName CliSessionWrite = "session-write"
cliOpcodeName CliSplit = "split"
cliOpcodeName CliWriteBuiltin = "write-builtin"

data SessionOpcode
  = SessionCapture
  | SessionFdClose
  | SessionFdData
  | SessionFdDup
  | SessionFdEndpoint
  | SessionFdOpen
  | SessionFdPop
  | SessionFdPush
  | SessionFdReset
  | SessionFinishSignal
  | SessionPing
  | SessionRead
  | SessionRun
  | SessionSpawn
  | SessionSubstitution
  | SessionSubstitutionRelease
  | SessionWait
  deriving stock (Show, Eq, Ord, Enum, Bounded)

sessionOpcodeName :: SessionOpcode -> String
sessionOpcodeName SessionCapture = "capture"
sessionOpcodeName SessionFdClose = "fd-close"
sessionOpcodeName SessionFdData = "fd-data"
sessionOpcodeName SessionFdDup = "fd-dup"
sessionOpcodeName SessionFdEndpoint = "fd-endpoint"
sessionOpcodeName SessionFdOpen = "fd-open"
sessionOpcodeName SessionFdPop = "fd-pop"
sessionOpcodeName SessionFdPush = "fd-push"
sessionOpcodeName SessionFdReset = "fd-reset"
sessionOpcodeName SessionFinishSignal = "finish-signal"
sessionOpcodeName SessionPing = "ping"
sessionOpcodeName SessionRead = "read"
sessionOpcodeName SessionRun = "run"
sessionOpcodeName SessionSpawn = "spawn"
sessionOpcodeName SessionSubstitution = "substitution"
sessionOpcodeName SessionSubstitutionRelease = "substitution-release"
sessionOpcodeName SessionWait = "wait"

data IntegerOpcode
  = IntegerAdd
  | IntegerAnd
  | IntegerBatch
  | IntegerDiv
  | IntegerEq
  | IntegerGe
  | IntegerGt
  | IntegerInvert
  | IntegerLe
  | IntegerLogicalAnd
  | IntegerLogicalOr
  | IntegerLt
  | IntegerMul
  | IntegerNe
  | IntegerNeg
  | IntegerNot
  | IntegerOr
  | IntegerPos
  | IntegerPow
  | IntegerPush
  | IntegerRead
  | IntegerRem
  | IntegerShl
  | IntegerShr
  | IntegerSub
  | IntegerXor
  deriving stock (Show, Eq, Ord, Enum, Bounded)

integerOpcodeName :: IntegerOpcode -> String
integerOpcodeName IntegerAdd = "add"
integerOpcodeName IntegerAnd = "and"
integerOpcodeName IntegerBatch = "batch"
integerOpcodeName IntegerDiv = "div"
integerOpcodeName IntegerEq = "eq"
integerOpcodeName IntegerGe = "ge"
integerOpcodeName IntegerGt = "gt"
integerOpcodeName IntegerInvert = "invert"
integerOpcodeName IntegerLe = "le"
integerOpcodeName IntegerLogicalAnd = "logical-and"
integerOpcodeName IntegerLogicalOr = "logical-or"
integerOpcodeName IntegerLt = "lt"
integerOpcodeName IntegerMul = "mul"
integerOpcodeName IntegerNe = "ne"
integerOpcodeName IntegerNeg = "neg"
integerOpcodeName IntegerNot = "not"
integerOpcodeName IntegerOr = "or"
integerOpcodeName IntegerPos = "pos"
integerOpcodeName IntegerPow = "pow"
integerOpcodeName IntegerPush = "push"
integerOpcodeName IntegerRead = "read"
integerOpcodeName IntegerRem = "rem"
integerOpcodeName IntegerShl = "shl"
integerOpcodeName IntegerShr = "shr"
integerOpcodeName IntegerSub = "sub"
integerOpcodeName IntegerXor = "xor"

data PatternOpcode
  = PatternMatch
  | PatternReplaceAll
  | PatternReplaceFirst
  | PatternTrimPrefixLong
  | PatternTrimPrefixShort
  | PatternTrimSuffixLong
  | PatternTrimSuffixShort
  deriving stock (Show, Eq, Ord, Enum, Bounded)

patternOpcodeName :: PatternOpcode -> String
patternOpcodeName PatternMatch = "match"
patternOpcodeName PatternReplaceAll = "replace-all"
patternOpcodeName PatternReplaceFirst = "replace-first"
patternOpcodeName PatternTrimPrefixLong = "trim-prefix-long"
patternOpcodeName PatternTrimPrefixShort = "trim-prefix-short"
patternOpcodeName PatternTrimSuffixLong = "trim-suffix-long"
patternOpcodeName PatternTrimSuffixShort = "trim-suffix-short"

data BodyOpcode
  = BodyBody
  | BodyBuiltin
  | BodyDirectoryOutput
  | BodyExternal
  | BodyExternalSite
  | BodyPipeline
  | BodySnapshot
  deriving stock (Show, Eq, Ord, Enum, Bounded)

bodyOpcodeName :: BodyOpcode -> String
bodyOpcodeName BodyBody = "body"
bodyOpcodeName BodyBuiltin = "builtin"
bodyOpcodeName BodyDirectoryOutput = "directory-output"
bodyOpcodeName BodyExternal = "external"
bodyOpcodeName BodyExternalSite = "external-site"
bodyOpcodeName BodyPipeline = "pipeline"
bodyOpcodeName BodySnapshot = "snapshot"
