// Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.
pub const ABI: usize = 2;
pub const PROFILE: &str = "bash53-i64";
pub const CAPABILITIES: &str = "argv bytes-platform child-capture child-run descriptor-state directory echo exec-site expansion glob integer launch pattern pattern-parts pipe-paths printf session split write-builtin";

pub mod opcode {
    pub mod cli {
        pub const ARGV: &[u8] = b"argv";
        pub const BYTES_PLATFORM: &[u8] = b"bytes-platform";
        pub const CHILD_CAPTURE: &[u8] = b"child-capture";
        pub const CHILD_CAPTURE_SESSION: &[u8] = b"child-capture-session";
        pub const CHILD_RUN: &[u8] = b"child-run";
        pub const CHILD_RUN_SESSION: &[u8] = b"child-run-session";
        pub const DESCRIPTOR_STATE: &[u8] = b"descriptor-state";
        pub const DIRECTORY_DIAGNOSTIC: &[u8] = b"directory-diagnostic";
        pub const DIRECTORY_INITIAL_OLDPWD: &[u8] = b"directory-initial-oldpwd";
        pub const DIRECTORY_PATH_BOUND: &[u8] = b"directory-path-bound";
        pub const DIRECTORY_PHYSICAL: &[u8] = b"directory-physical";
        pub const DIRECTORY_STACK: &[u8] = b"directory-stack";
        pub const DIRECTORY_VALIDATE: &[u8] = b"directory-validate";
        pub const ECHO: &[u8] = b"echo";
        pub const EXEC_SITE: &[u8] = b"exec-site";
        pub const EXPANSION: &[u8] = b"expansion";
        pub const GLOB: &[u8] = b"glob";
        pub const INTEGER: &[u8] = b"integer";
        pub const LAUNCH: &[u8] = b"launch";
        pub const PATTERN: &[u8] = b"pattern";
        pub const PATTERN_PARTS: &[u8] = b"pattern-parts";
        pub const PIPE_PATHS: &[u8] = b"pipe-paths";
        pub const PRINTF: &[u8] = b"printf";
        pub const RAISE_SIGNAL: &[u8] = b"raise-signal";
        pub const SESSION_CLIENT: &[u8] = b"session-client";
        pub const SESSION_DIRECTORY_DIAGNOSTIC: &[u8] = b"session-directory-diagnostic";
        pub const SESSION_EXEC_ERROR: &[u8] = b"session-exec-error";
        pub const SESSION_GUARDIAN: &[u8] = b"session-guardian";
        pub const SESSION_PREPARE: &[u8] = b"session-prepare";
        pub const SESSION_RUN: &[u8] = b"session-run";
        pub const SESSION_WRITE: &[u8] = b"session-write";
        pub const SPLIT: &[u8] = b"split";
        pub const WRITE_BUILTIN: &[u8] = b"write-builtin";

        pub const ALL: &[&[u8]] = &[
            ARGV,
            BYTES_PLATFORM,
            CHILD_CAPTURE,
            CHILD_CAPTURE_SESSION,
            CHILD_RUN,
            CHILD_RUN_SESSION,
            DESCRIPTOR_STATE,
            DIRECTORY_DIAGNOSTIC,
            DIRECTORY_INITIAL_OLDPWD,
            DIRECTORY_PATH_BOUND,
            DIRECTORY_PHYSICAL,
            DIRECTORY_STACK,
            DIRECTORY_VALIDATE,
            ECHO,
            EXEC_SITE,
            EXPANSION,
            GLOB,
            INTEGER,
            LAUNCH,
            PATTERN,
            PATTERN_PARTS,
            PIPE_PATHS,
            PRINTF,
            RAISE_SIGNAL,
            SESSION_CLIENT,
            SESSION_DIRECTORY_DIAGNOSTIC,
            SESSION_EXEC_ERROR,
            SESSION_GUARDIAN,
            SESSION_PREPARE,
            SESSION_RUN,
            SESSION_WRITE,
            SPLIT,
            WRITE_BUILTIN,
        ];

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Opcode {
            Argv,
            BytesPlatform,
            ChildCapture,
            ChildCaptureSession,
            ChildRun,
            ChildRunSession,
            DescriptorState,
            DirectoryDiagnostic,
            DirectoryInitialOldpwd,
            DirectoryPathBound,
            DirectoryPhysical,
            DirectoryStack,
            DirectoryValidate,
            Echo,
            ExecSite,
            Expansion,
            Glob,
            Integer,
            Launch,
            Pattern,
            PatternParts,
            PipePaths,
            Printf,
            RaiseSignal,
            SessionClient,
            SessionDirectoryDiagnostic,
            SessionExecError,
            SessionGuardian,
            SessionPrepare,
            SessionRun,
            SessionWrite,
            Split,
            WriteBuiltin,
        }

        impl Opcode {
            pub const fn as_bytes(self) -> &'static [u8] {
                match self {
                    Self::Argv => ARGV,
                    Self::BytesPlatform => BYTES_PLATFORM,
                    Self::ChildCapture => CHILD_CAPTURE,
                    Self::ChildCaptureSession => CHILD_CAPTURE_SESSION,
                    Self::ChildRun => CHILD_RUN,
                    Self::ChildRunSession => CHILD_RUN_SESSION,
                    Self::DescriptorState => DESCRIPTOR_STATE,
                    Self::DirectoryDiagnostic => DIRECTORY_DIAGNOSTIC,
                    Self::DirectoryInitialOldpwd => DIRECTORY_INITIAL_OLDPWD,
                    Self::DirectoryPathBound => DIRECTORY_PATH_BOUND,
                    Self::DirectoryPhysical => DIRECTORY_PHYSICAL,
                    Self::DirectoryStack => DIRECTORY_STACK,
                    Self::DirectoryValidate => DIRECTORY_VALIDATE,
                    Self::Echo => ECHO,
                    Self::ExecSite => EXEC_SITE,
                    Self::Expansion => EXPANSION,
                    Self::Glob => GLOB,
                    Self::Integer => INTEGER,
                    Self::Launch => LAUNCH,
                    Self::Pattern => PATTERN,
                    Self::PatternParts => PATTERN_PARTS,
                    Self::PipePaths => PIPE_PATHS,
                    Self::Printf => PRINTF,
                    Self::RaiseSignal => RAISE_SIGNAL,
                    Self::SessionClient => SESSION_CLIENT,
                    Self::SessionDirectoryDiagnostic => SESSION_DIRECTORY_DIAGNOSTIC,
                    Self::SessionExecError => SESSION_EXEC_ERROR,
                    Self::SessionGuardian => SESSION_GUARDIAN,
                    Self::SessionPrepare => SESSION_PREPARE,
                    Self::SessionRun => SESSION_RUN,
                    Self::SessionWrite => SESSION_WRITE,
                    Self::Split => SPLIT,
                    Self::WriteBuiltin => WRITE_BUILTIN,
                }
            }

            pub fn parse(bytes: &[u8]) -> Option<Self> {
                match bytes {
                    ARGV => Some(Self::Argv),
                    BYTES_PLATFORM => Some(Self::BytesPlatform),
                    CHILD_CAPTURE => Some(Self::ChildCapture),
                    CHILD_CAPTURE_SESSION => Some(Self::ChildCaptureSession),
                    CHILD_RUN => Some(Self::ChildRun),
                    CHILD_RUN_SESSION => Some(Self::ChildRunSession),
                    DESCRIPTOR_STATE => Some(Self::DescriptorState),
                    DIRECTORY_DIAGNOSTIC => Some(Self::DirectoryDiagnostic),
                    DIRECTORY_INITIAL_OLDPWD => Some(Self::DirectoryInitialOldpwd),
                    DIRECTORY_PATH_BOUND => Some(Self::DirectoryPathBound),
                    DIRECTORY_PHYSICAL => Some(Self::DirectoryPhysical),
                    DIRECTORY_STACK => Some(Self::DirectoryStack),
                    DIRECTORY_VALIDATE => Some(Self::DirectoryValidate),
                    ECHO => Some(Self::Echo),
                    EXEC_SITE => Some(Self::ExecSite),
                    EXPANSION => Some(Self::Expansion),
                    GLOB => Some(Self::Glob),
                    INTEGER => Some(Self::Integer),
                    LAUNCH => Some(Self::Launch),
                    PATTERN => Some(Self::Pattern),
                    PATTERN_PARTS => Some(Self::PatternParts),
                    PIPE_PATHS => Some(Self::PipePaths),
                    PRINTF => Some(Self::Printf),
                    RAISE_SIGNAL => Some(Self::RaiseSignal),
                    SESSION_CLIENT => Some(Self::SessionClient),
                    SESSION_DIRECTORY_DIAGNOSTIC => Some(Self::SessionDirectoryDiagnostic),
                    SESSION_EXEC_ERROR => Some(Self::SessionExecError),
                    SESSION_GUARDIAN => Some(Self::SessionGuardian),
                    SESSION_PREPARE => Some(Self::SessionPrepare),
                    SESSION_RUN => Some(Self::SessionRun),
                    SESSION_WRITE => Some(Self::SessionWrite),
                    SPLIT => Some(Self::Split),
                    WRITE_BUILTIN => Some(Self::WriteBuiltin),
                    _ => None,
                }
            }
        }
    }
    pub mod session {
        pub const CAPTURE: &[u8] = b"capture";
        pub const FD_CLOSE: &[u8] = b"fd-close";
        pub const FD_DATA: &[u8] = b"fd-data";
        pub const FD_DUP: &[u8] = b"fd-dup";
        pub const FD_ENDPOINT: &[u8] = b"fd-endpoint";
        pub const FD_OPEN: &[u8] = b"fd-open";
        pub const FD_POP: &[u8] = b"fd-pop";
        pub const FD_PUSH: &[u8] = b"fd-push";
        pub const FD_RESET: &[u8] = b"fd-reset";
        pub const FINISH_SIGNAL: &[u8] = b"finish-signal";
        pub const PING: &[u8] = b"ping";
        pub const READ: &[u8] = b"read";
        pub const RUN: &[u8] = b"run";
        pub const SPAWN: &[u8] = b"spawn";
        pub const SUBSTITUTION: &[u8] = b"substitution";
        pub const SUBSTITUTION_RELEASE: &[u8] = b"substitution-release";
        pub const WAIT: &[u8] = b"wait";

        pub const ALL: &[&[u8]] = &[
            CAPTURE,
            FD_CLOSE,
            FD_DATA,
            FD_DUP,
            FD_ENDPOINT,
            FD_OPEN,
            FD_POP,
            FD_PUSH,
            FD_RESET,
            FINISH_SIGNAL,
            PING,
            READ,
            RUN,
            SPAWN,
            SUBSTITUTION,
            SUBSTITUTION_RELEASE,
            WAIT,
        ];

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Opcode {
            Capture,
            FdClose,
            FdData,
            FdDup,
            FdEndpoint,
            FdOpen,
            FdPop,
            FdPush,
            FdReset,
            FinishSignal,
            Ping,
            Read,
            Run,
            Spawn,
            Substitution,
            SubstitutionRelease,
            Wait,
        }

        impl Opcode {
            pub const fn as_bytes(self) -> &'static [u8] {
                match self {
                    Self::Capture => CAPTURE,
                    Self::FdClose => FD_CLOSE,
                    Self::FdData => FD_DATA,
                    Self::FdDup => FD_DUP,
                    Self::FdEndpoint => FD_ENDPOINT,
                    Self::FdOpen => FD_OPEN,
                    Self::FdPop => FD_POP,
                    Self::FdPush => FD_PUSH,
                    Self::FdReset => FD_RESET,
                    Self::FinishSignal => FINISH_SIGNAL,
                    Self::Ping => PING,
                    Self::Read => READ,
                    Self::Run => RUN,
                    Self::Spawn => SPAWN,
                    Self::Substitution => SUBSTITUTION,
                    Self::SubstitutionRelease => SUBSTITUTION_RELEASE,
                    Self::Wait => WAIT,
                }
            }

            pub fn parse(bytes: &[u8]) -> Option<Self> {
                match bytes {
                    CAPTURE => Some(Self::Capture),
                    FD_CLOSE => Some(Self::FdClose),
                    FD_DATA => Some(Self::FdData),
                    FD_DUP => Some(Self::FdDup),
                    FD_ENDPOINT => Some(Self::FdEndpoint),
                    FD_OPEN => Some(Self::FdOpen),
                    FD_POP => Some(Self::FdPop),
                    FD_PUSH => Some(Self::FdPush),
                    FD_RESET => Some(Self::FdReset),
                    FINISH_SIGNAL => Some(Self::FinishSignal),
                    PING => Some(Self::Ping),
                    READ => Some(Self::Read),
                    RUN => Some(Self::Run),
                    SPAWN => Some(Self::Spawn),
                    SUBSTITUTION => Some(Self::Substitution),
                    SUBSTITUTION_RELEASE => Some(Self::SubstitutionRelease),
                    WAIT => Some(Self::Wait),
                    _ => None,
                }
            }
        }
    }
    pub mod integer {
        pub const ADD: &[u8] = b"add";
        pub const AND: &[u8] = b"and";
        pub const BATCH: &[u8] = b"batch";
        pub const DIV: &[u8] = b"div";
        pub const EQ: &[u8] = b"eq";
        pub const GE: &[u8] = b"ge";
        pub const GT: &[u8] = b"gt";
        pub const INVERT: &[u8] = b"invert";
        pub const LE: &[u8] = b"le";
        pub const LOGICAL_AND: &[u8] = b"logical-and";
        pub const LOGICAL_OR: &[u8] = b"logical-or";
        pub const LT: &[u8] = b"lt";
        pub const MUL: &[u8] = b"mul";
        pub const NE: &[u8] = b"ne";
        pub const NEG: &[u8] = b"neg";
        pub const NOT: &[u8] = b"not";
        pub const OR: &[u8] = b"or";
        pub const POS: &[u8] = b"pos";
        pub const POW: &[u8] = b"pow";
        pub const PUSH: &[u8] = b"push";
        pub const READ: &[u8] = b"read";
        pub const REM: &[u8] = b"rem";
        pub const SHL: &[u8] = b"shl";
        pub const SHR: &[u8] = b"shr";
        pub const SUB: &[u8] = b"sub";
        pub const XOR: &[u8] = b"xor";

        pub const ALL: &[&[u8]] = &[
            ADD,
            AND,
            BATCH,
            DIV,
            EQ,
            GE,
            GT,
            INVERT,
            LE,
            LOGICAL_AND,
            LOGICAL_OR,
            LT,
            MUL,
            NE,
            NEG,
            NOT,
            OR,
            POS,
            POW,
            PUSH,
            READ,
            REM,
            SHL,
            SHR,
            SUB,
            XOR,
        ];

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Opcode {
            Add,
            And,
            Batch,
            Div,
            Eq,
            Ge,
            Gt,
            Invert,
            Le,
            LogicalAnd,
            LogicalOr,
            Lt,
            Mul,
            Ne,
            Neg,
            Not,
            Or,
            Pos,
            Pow,
            Push,
            Read,
            Rem,
            Shl,
            Shr,
            Sub,
            Xor,
        }

        impl Opcode {
            pub const fn as_bytes(self) -> &'static [u8] {
                match self {
                    Self::Add => ADD,
                    Self::And => AND,
                    Self::Batch => BATCH,
                    Self::Div => DIV,
                    Self::Eq => EQ,
                    Self::Ge => GE,
                    Self::Gt => GT,
                    Self::Invert => INVERT,
                    Self::Le => LE,
                    Self::LogicalAnd => LOGICAL_AND,
                    Self::LogicalOr => LOGICAL_OR,
                    Self::Lt => LT,
                    Self::Mul => MUL,
                    Self::Ne => NE,
                    Self::Neg => NEG,
                    Self::Not => NOT,
                    Self::Or => OR,
                    Self::Pos => POS,
                    Self::Pow => POW,
                    Self::Push => PUSH,
                    Self::Read => READ,
                    Self::Rem => REM,
                    Self::Shl => SHL,
                    Self::Shr => SHR,
                    Self::Sub => SUB,
                    Self::Xor => XOR,
                }
            }

            pub fn parse(bytes: &[u8]) -> Option<Self> {
                match bytes {
                    ADD => Some(Self::Add),
                    AND => Some(Self::And),
                    BATCH => Some(Self::Batch),
                    DIV => Some(Self::Div),
                    EQ => Some(Self::Eq),
                    GE => Some(Self::Ge),
                    GT => Some(Self::Gt),
                    INVERT => Some(Self::Invert),
                    LE => Some(Self::Le),
                    LOGICAL_AND => Some(Self::LogicalAnd),
                    LOGICAL_OR => Some(Self::LogicalOr),
                    LT => Some(Self::Lt),
                    MUL => Some(Self::Mul),
                    NE => Some(Self::Ne),
                    NEG => Some(Self::Neg),
                    NOT => Some(Self::Not),
                    OR => Some(Self::Or),
                    POS => Some(Self::Pos),
                    POW => Some(Self::Pow),
                    PUSH => Some(Self::Push),
                    READ => Some(Self::Read),
                    REM => Some(Self::Rem),
                    SHL => Some(Self::Shl),
                    SHR => Some(Self::Shr),
                    SUB => Some(Self::Sub),
                    XOR => Some(Self::Xor),
                    _ => None,
                }
            }
        }
    }
    pub mod pattern {
        pub const MATCH: &[u8] = b"match";
        pub const REPLACE_ALL: &[u8] = b"replace-all";
        pub const REPLACE_FIRST: &[u8] = b"replace-first";
        pub const TRIM_PREFIX_LONG: &[u8] = b"trim-prefix-long";
        pub const TRIM_PREFIX_SHORT: &[u8] = b"trim-prefix-short";
        pub const TRIM_SUFFIX_LONG: &[u8] = b"trim-suffix-long";
        pub const TRIM_SUFFIX_SHORT: &[u8] = b"trim-suffix-short";

        pub const ALL: &[&[u8]] = &[
            MATCH,
            REPLACE_ALL,
            REPLACE_FIRST,
            TRIM_PREFIX_LONG,
            TRIM_PREFIX_SHORT,
            TRIM_SUFFIX_LONG,
            TRIM_SUFFIX_SHORT,
        ];

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Opcode {
            Match,
            ReplaceAll,
            ReplaceFirst,
            TrimPrefixLong,
            TrimPrefixShort,
            TrimSuffixLong,
            TrimSuffixShort,
        }

        impl Opcode {
            pub const fn as_bytes(self) -> &'static [u8] {
                match self {
                    Self::Match => MATCH,
                    Self::ReplaceAll => REPLACE_ALL,
                    Self::ReplaceFirst => REPLACE_FIRST,
                    Self::TrimPrefixLong => TRIM_PREFIX_LONG,
                    Self::TrimPrefixShort => TRIM_PREFIX_SHORT,
                    Self::TrimSuffixLong => TRIM_SUFFIX_LONG,
                    Self::TrimSuffixShort => TRIM_SUFFIX_SHORT,
                }
            }

            pub fn parse(bytes: &[u8]) -> Option<Self> {
                match bytes {
                    MATCH => Some(Self::Match),
                    REPLACE_ALL => Some(Self::ReplaceAll),
                    REPLACE_FIRST => Some(Self::ReplaceFirst),
                    TRIM_PREFIX_LONG => Some(Self::TrimPrefixLong),
                    TRIM_PREFIX_SHORT => Some(Self::TrimPrefixShort),
                    TRIM_SUFFIX_LONG => Some(Self::TrimSuffixLong),
                    TRIM_SUFFIX_SHORT => Some(Self::TrimSuffixShort),
                    _ => None,
                }
            }
        }
    }
    pub mod body {
        pub const BODY: &[u8] = b"body";
        pub const BUILTIN: &[u8] = b"builtin";
        pub const DIRECTORY_OUTPUT: &[u8] = b"directory-output";
        pub const EXTERNAL: &[u8] = b"external";
        pub const EXTERNAL_SITE: &[u8] = b"external-site";
        pub const PIPELINE: &[u8] = b"pipeline";
        pub const SNAPSHOT: &[u8] = b"snapshot";

        pub const ALL: &[&[u8]] = &[
            BODY,
            BUILTIN,
            DIRECTORY_OUTPUT,
            EXTERNAL,
            EXTERNAL_SITE,
            PIPELINE,
            SNAPSHOT,
        ];

        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Opcode {
            Body,
            Builtin,
            DirectoryOutput,
            External,
            ExternalSite,
            Pipeline,
            Snapshot,
        }

        impl Opcode {
            pub const fn as_bytes(self) -> &'static [u8] {
                match self {
                    Self::Body => BODY,
                    Self::Builtin => BUILTIN,
                    Self::DirectoryOutput => DIRECTORY_OUTPUT,
                    Self::External => EXTERNAL,
                    Self::ExternalSite => EXTERNAL_SITE,
                    Self::Pipeline => PIPELINE,
                    Self::Snapshot => SNAPSHOT,
                }
            }

            pub fn parse(bytes: &[u8]) -> Option<Self> {
                match bytes {
                    BODY => Some(Self::Body),
                    BUILTIN => Some(Self::Builtin),
                    DIRECTORY_OUTPUT => Some(Self::DirectoryOutput),
                    EXTERNAL => Some(Self::External),
                    EXTERNAL_SITE => Some(Self::ExternalSite),
                    PIPELINE => Some(Self::Pipeline),
                    SNAPSHOT => Some(Self::Snapshot),
                    _ => None,
                }
            }
        }
    }
}

pub const OPCODES: &[(&str, &[&[u8]])] = &[
    ("cli", opcode::cli::ALL),
    ("session", opcode::session::ALL),
    ("integer", opcode::integer::ALL),
    ("pattern", opcode::pattern::ALL),
    ("body", opcode::body::ALL),
];

pub fn target() -> Option<&'static str> {
    #[cfg(all(target_arch = "x86_64", target_os = "linux"))]
    {
        Some("x86_64-linux")
    }
    #[cfg(all(target_arch = "aarch64", target_os = "linux"))]
    {
        Some("aarch64-linux")
    }
    #[cfg(all(target_arch = "aarch64", target_os = "macos"))]
    {
        Some("aarch64-darwin")
    }
    #[cfg(not(any(
        all(target_arch = "x86_64", target_os = "linux"),
        all(target_arch = "aarch64", target_os = "linux"),
        all(target_arch = "aarch64", target_os = "macos")
    )))]
    {
        None
    }
}

pub fn description() -> Option<String> {
    target()
        .map(|target| format!("monk-runtime {ABI} {PROFILE}\n{CAPABILITIES}\ntarget {target}\n"))
}
