// Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.
pub const ABI: usize = 2;
pub const PROFILE: &str = "bash53-i64";
pub const CAPABILITIES: &str = "argv bytes-platform child-capture child-run descriptor-state directory echo exec-site expansion glob integer launch pattern pattern-parts pipe-paths printf session split write-builtin";

pub mod opcode {
    pub mod cli {
        pub const ARGV: &[u8] = b"argv";
        pub const BYTES_PLATFORM: &[u8] = b"bytes-platform";
        pub const CHILD_CAPTURE: &[u8] = b"child-capture";
        pub const CHILD_CAPTURE_SESSION: &[u8] = b"child-capture-session";
        pub const CHILD_RUN: &[u8] = b"child-run";
        pub const CHILD_RUN_SESSION: &[u8] = b"child-run-session";
        pub const DESCRIPTOR_STATE: &[u8] = b"descriptor-state";
        pub const DIRECTORY_DIAGNOSTIC: &[u8] = b"directory-diagnostic";
        pub const DIRECTORY_INITIAL_OLDPWD: &[u8] = b"directory-initial-oldpwd";
        pub const DIRECTORY_PATH_BOUND: &[u8] = b"directory-path-bound";
        pub const DIRECTORY_PHYSICAL: &[u8] = b"directory-physical";
        pub const DIRECTORY_STACK: &[u8] = b"directory-stack";
        pub const DIRECTORY_VALIDATE: &[u8] = b"directory-validate";
        pub const ECHO: &[u8] = b"echo";
        pub const EXEC_SITE: &[u8] = b"exec-site";
        pub const EXPANSION: &[u8] = b"expansion";
        pub const GLOB: &[u8] = b"glob";
        pub const INTEGER: &[u8] = b"integer";
        pub const LAUNCH: &[u8] = b"launch";
        pub const PATTERN: &[u8] = b"pattern";
        pub const PATTERN_PARTS: &[u8] = b"pattern-parts";
        pub const PIPE_PATHS: &[u8] = b"pipe-paths";
        pub const PRINTF: &[u8] = b"printf";
        pub const RAISE_SIGNAL: &[u8] = b"raise-signal";
        pub const SESSION_CLIENT: &[u8] = b"session-client";
        pub const SESSION_DIRECTORY_DIAGNOSTIC: &[u8] = b"session-directory-diagnostic";
        pub const SESSION_EXEC_ERROR: &[u8] = b"session-exec-error";
        pub const SESSION_GUARDIAN: &[u8] = b"session-guardian";
        pub const SESSION_PREPARE: &[u8] = b"session-prepare";
        pub const SESSION_RUN: &[u8] = b"session-run";
        pub const SESSION_WRITE: &[u8] = b"session-write";
        pub const SPLIT: &[u8] = b"split";
        pub const WRITE_BUILTIN: &[u8] = b"write-builtin";

        pub const ALL: &[&[u8]] = &[
            ARGV,
            BYTES_PLATFORM,
            CHILD_CAPTURE,
            CHILD_CAPTURE_SESSION,
            CHILD_RUN,
            CHILD_RUN_SESSION,
            DESCRIPTOR_STATE,
            DIRECTORY_DIAGNOSTIC,
            DIRECTORY_INITIAL_OLDPWD,
            DIRECTORY_PATH_BOUND,
            DIRECTORY_PHYSICAL,
            DIRECTORY_STACK,
            DIRECTORY_VALIDATE,
            ECHO,
            EXEC_SITE,
            EXPANSION,
            GLOB,
            INTEGER,
            LAUNCH,
            PATTERN,
            PATTERN_PARTS,
            PIPE_PATHS,
            PRINTF,
            RAISE_SIGNAL,
            SESSION_CLIENT,
            SESSION_DIRECTORY_DIAGNOSTIC,
            SESSION_EXEC_ERROR,
            SESSION_GUARDIAN,
            SESSION_PREPARE,
            SESSION_RUN,
            SESSION_WRITE,
            SPLIT,
            WRITE_BUILTIN,
        ];
    }
    pub mod session {
        pub const CAPTURE: &[u8] = b"capture";
        pub const FD_CLOSE: &[u8] = b"fd-close";
        pub const FD_DATA: &[u8] = b"fd-data";
        pub const FD_DUP: &[u8] = b"fd-dup";
        pub const FD_ENDPOINT: &[u8] = b"fd-endpoint";
        pub const FD_OPEN: &[u8] = b"fd-open";
        pub const FD_POP: &[u8] = b"fd-pop";
        pub const FD_PUSH: &[u8] = b"fd-push";
        pub const FD_RESET: &[u8] = b"fd-reset";
        pub const FINISH_SIGNAL: &[u8] = b"finish-signal";
        pub const PING: &[u8] = b"ping";
        pub const READ: &[u8] = b"read";
        pub const RUN: &[u8] = b"run";
        pub const SPAWN: &[u8] = b"spawn";
        pub const SUBSTITUTION: &[u8] = b"substitution";
        pub const SUBSTITUTION_RELEASE: &[u8] = b"substitution-release";
        pub const WAIT: &[u8] = b"wait";

        pub const ALL: &[&[u8]] = &[
            CAPTURE,
            FD_CLOSE,
            FD_DATA,
            FD_DUP,
            FD_ENDPOINT,
            FD_OPEN,
            FD_POP,
            FD_PUSH,
            FD_RESET,
            FINISH_SIGNAL,
            PING,
            READ,
            RUN,
            SPAWN,
            SUBSTITUTION,
            SUBSTITUTION_RELEASE,
            WAIT,
        ];
    }
    pub mod integer {
        pub const ADD: &[u8] = b"add";
        pub const AND: &[u8] = b"and";
        pub const BATCH: &[u8] = b"batch";
        pub const DIV: &[u8] = b"div";
        pub const EQ: &[u8] = b"eq";
        pub const GE: &[u8] = b"ge";
        pub const GT: &[u8] = b"gt";
        pub const INVERT: &[u8] = b"invert";
        pub const LE: &[u8] = b"le";
        pub const LOGICAL_AND: &[u8] = b"logical-and";
        pub const LOGICAL_OR: &[u8] = b"logical-or";
        pub const LT: &[u8] = b"lt";
        pub const MUL: &[u8] = b"mul";
        pub const NE: &[u8] = b"ne";
        pub const NEG: &[u8] = b"neg";
        pub const NOT: &[u8] = b"not";
        pub const OR: &[u8] = b"or";
        pub const POS: &[u8] = b"pos";
        pub const POW: &[u8] = b"pow";
        pub const PUSH: &[u8] = b"push";
        pub const READ: &[u8] = b"read";
        pub const REM: &[u8] = b"rem";
        pub const SHL: &[u8] = b"shl";
        pub const SHR: &[u8] = b"shr";
        pub const SUB: &[u8] = b"sub";
        pub const XOR: &[u8] = b"xor";

        pub const ALL: &[&[u8]] = &[
            ADD,
            AND,
            BATCH,
            DIV,
            EQ,
            GE,
            GT,
            INVERT,
            LE,
            LOGICAL_AND,
            LOGICAL_OR,
            LT,
            MUL,
            NE,
            NEG,
            NOT,
            OR,
            POS,
            POW,
            PUSH,
            READ,
            REM,
            SHL,
            SHR,
            SUB,
            XOR,
        ];
    }
    pub mod pattern {
        pub const MATCH: &[u8] = b"match";
        pub const REPLACE_ALL: &[u8] = b"replace-all";
        pub const REPLACE_FIRST: &[u8] = b"replace-first";
        pub const TRIM_PREFIX_LONG: &[u8] = b"trim-prefix-long";
        pub const TRIM_PREFIX_SHORT: &[u8] = b"trim-prefix-short";
        pub const TRIM_SUFFIX_LONG: &[u8] = b"trim-suffix-long";
        pub const TRIM_SUFFIX_SHORT: &[u8] = b"trim-suffix-short";

        pub const ALL: &[&[u8]] = &[
            MATCH,
            REPLACE_ALL,
            REPLACE_FIRST,
            TRIM_PREFIX_LONG,
            TRIM_PREFIX_SHORT,
            TRIM_SUFFIX_LONG,
            TRIM_SUFFIX_SHORT,
        ];
    }
    pub mod body {
        pub const BODY: &[u8] = b"body";
        pub const BUILTIN: &[u8] = b"builtin";
        pub const DIRECTORY_OUTPUT: &[u8] = b"directory-output";
        pub const EXTERNAL: &[u8] = b"external";
        pub const EXTERNAL_SITE: &[u8] = b"external-site";
        pub const PIPELINE: &[u8] = b"pipeline";
        pub const SNAPSHOT: &[u8] = b"snapshot";

        pub const ALL: &[&[u8]] = &[
            BODY,
            BUILTIN,
            DIRECTORY_OUTPUT,
            EXTERNAL,
            EXTERNAL_SITE,
            PIPELINE,
            SNAPSHOT,
        ];
    }
}

pub const OPCODES: &[(&str, &[&[u8]])] = &[
    ("cli", opcode::cli::ALL),
    ("session", opcode::session::ALL),
    ("integer", opcode::integer::ALL),
    ("pattern", opcode::pattern::ALL),
    ("body", opcode::body::ALL),
];

pub fn target() -> Option<&'static str> {
    #[cfg(all(target_arch = "x86_64", target_os = "linux"))]
    {
        Some("x86_64-linux")
    }
    #[cfg(all(target_arch = "aarch64", target_os = "linux"))]
    {
        Some("aarch64-linux")
    }
    #[cfg(all(target_arch = "aarch64", target_os = "macos"))]
    {
        Some("aarch64-darwin")
    }
    #[cfg(not(any(
        all(target_arch = "x86_64", target_os = "linux"),
        all(target_arch = "aarch64", target_os = "linux"),
        all(target_arch = "aarch64", target_os = "macos")
    )))]
    {
        None
    }
}

pub fn description() -> Option<String> {
    target()
        .map(|target| format!("monk-runtime {ABI} {PROFILE}\n{CAPABILITIES}\ntarget {target}\n"))
}
