#!/usr/bin/env bash
set -euo pipefail

case ${1:-} in
  ''|--write) mode='write' ;;
  --check) mode=check ;;
  *) printf 'usage: %s [--write|--check]\n' "$0" >&2; exit 2 ;;
esac

source_file=protocol/abi2.tsv
haskell_file=support-src/Monk/Runtime/Abi2.hs
rust_file=runtime/src/abi2.rs
temporary=$(mktemp -d)
trap 'rm -rf "$temporary"' EXIT

abi=
profile=
targets=()
constructors=()
operation_names=()
capabilities=()
opcode_namespaces=()
opcode_names=()
namespaces=(cli session integer pattern body)
namespace_counts=(33 17 26 7 7)
while read -r kind first second extra; do
  [[ -z $kind || $kind == \#* ]] && continue
  [[ -z ${extra:-} ]] || { printf 'extra ABI metadata field\n' >&2; exit 1; }
  case $kind in
    abi) [[ $first =~ ^[0-9]+$ && -z ${second:-} && -z $abi ]] || exit 1; abi=$first ;;
    profile) [[ $first =~ ^[a-z0-9-]+$ && -z ${second:-} && -z $profile ]] || exit 1; profile=$first ;;
    target) [[ $first =~ ^[a-z0-9_-]+$ && -z ${second:-} ]] || exit 1; targets+=("$first") ;;
    capability) [[ $first =~ ^[a-z0-9-]+$ && -z ${second:-} ]] || exit 1; capabilities+=("$first") ;;
    operation) [[ $first =~ ^Native[A-Za-z]+$ && $second =~ ^[a-z0-9-]+$ ]] || exit 1; constructors+=("$first"); operation_names+=("$second"); capabilities+=("$second") ;;
    opcode)
      [[ $first == cli || $first == session || $first == integer || $first == pattern || $first == body ]] || { printf 'unknown opcode namespace: %s\n' "$first" >&2; exit 1; }
      [[ $second =~ ^[a-z][a-z0-9]*(-[a-z0-9]+)*$ ]] || { printf 'invalid opcode spelling\n' >&2; exit 1; }
      opcode_namespaces+=("$first"); opcode_names+=("$second") ;;
    *) printf 'unknown ABI metadata kind: %s\n' "$kind" >&2; exit 1 ;;
  esac
done < "$source_file"
[[ $abi == 2 && $profile == bash53-i64 && ${#targets[@]} == 3 && ${#constructors[@]} == 18 && ${#capabilities[@]} == 19 ]] || { printf 'incomplete ABI metadata\n' >&2; exit 1; }
[[ ${targets[*]} == 'x86_64-linux aarch64-linux aarch64-darwin' ]] || { printf 'target generator needs an update\n' >&2; exit 1; }
[[ $(printf '%s\n' "${constructors[@]}" | sort -u | wc -l | tr -d ' ') == "${#constructors[@]}" ]] || exit 1
[[ $(printf '%s\n' "${capabilities[@]}" | sort -u | wc -l | tr -d ' ') == "${#capabilities[@]}" ]] || exit 1
sed -n '/^data NativeOperation$/,/deriving stock/p' src/Monk/Translation/Types.hs | grep -Eo 'Native[A-Za-z]+' | grep -v '^NativeOperation$' | LC_ALL=C sort -u > "$temporary/declared-operations"
printf '%s\n' "${constructors[@]}" | LC_ALL=C sort -u > "$temporary/mapped-operations"
cmp "$temporary/declared-operations" "$temporary/mapped-operations"
capability_line=$(printf '%s\n' "${capabilities[@]}" | LC_ALL=C sort | paste -sd ' ' -)

# ABI 2 has a closed opcode inventory. Cross-namespace repetitions such as read
# are valid; duplicates within a namespace, missing rows and unknown namespaces
# are rejected before either committed output can be overwritten.
for namespace_index in "${!namespaces[@]}"; do
  namespace=${namespaces[namespace_index]}
  count=0
  : > "$temporary/opcodes-$namespace"
  for index in "${!opcode_names[@]}"; do
    if [[ ${opcode_namespaces[index]} == "$namespace" ]]; then
      printf '%s\n' "${opcode_names[index]}" >> "$temporary/opcodes-$namespace"
      count=$((count + 1))
    fi
  done
  [[ $(LC_ALL=C sort -u "$temporary/opcodes-$namespace" | wc -l | tr -d ' ') == "$count" ]] || { printf 'duplicate opcode in %s\n' "$namespace" >&2; exit 1; }
  [[ $count == "${namespace_counts[namespace_index]}" ]] || { printf 'incomplete %s opcode metadata: expected %s, got %s\n' "$namespace" "${namespace_counts[namespace_index]}" "$count" >&2; exit 1; }
  LC_ALL=C sort "$temporary/opcodes-$namespace" > "$temporary/sorted-opcodes-$namespace"
done

{
  printf '%s\n' '-- Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.'
  printf '%s\n' 'module Monk.Runtime.Abi2 (abiVersion, abiProfile, abiCapabilities, abiTargets, abiOperationName, abiOpcodes) where'
  printf '\nabiVersion :: Int\nabiVersion = %s\n' "$abi"
  printf '\nabiProfile :: String\nabiProfile = "%s"\n' "$profile"
  printf '\nabiCapabilities :: String\nabiCapabilities = "%s"\n' "$capability_line"
  printf '\nabiTargets :: [String]\nabiTargets = ['
  separator=''
  for target in "${targets[@]}"; do printf '%s"%s"' "$separator" "$target"; separator=', '; done
  printf ']\n'
  printf '\nabiOperationName :: String -> Maybe String\n'
  for index in "${!constructors[@]}"; do printf 'abiOperationName "%s" = Just "%s"\n' "${constructors[index]}" "${operation_names[index]}"; done
  printf '%s\n' 'abiOperationName _ = Nothing'
  printf '\nabiOpcodes :: [(String, String)]\nabiOpcodes =\n'
  separator='  [ '
  for namespace in "${namespaces[@]}"; do
    while read -r name; do
      printf '%s("%s", "%s")' "$separator" "$namespace" "$name"
      separator=$',\n    '
    done < "$temporary/sorted-opcodes-$namespace"
  done
  printf '\n  ]\n'
} > "$temporary/Abi2.hs"

{
  printf '%s\n' '// Generated by scripts/generate-abi-metadata.sh from protocol/abi2.tsv.'
  printf 'pub const ABI: usize = %s;\n' "$abi"
  printf 'pub const PROFILE: &str = "%s";\n' "$profile"
  printf 'pub const CAPABILITIES: &str = "%s";\n' "$capability_line"
  printf '\npub mod opcode {\n'
  for namespace in "${namespaces[@]}"; do
    printf '    pub mod %s {\n' "$namespace"
    while read -r name; do
      constant=$(printf '%s' "$name" | LC_ALL=C tr 'a-z-' 'A-Z_')
      printf '        pub const %s: &[u8] = b"%s";\n' "$constant" "$name"
    done < "$temporary/sorted-opcodes-$namespace"
    printf '\n        pub const ALL: &[&[u8]] = &[\n'
    while read -r name; do
      constant=$(printf '%s' "$name" | LC_ALL=C tr 'a-z-' 'A-Z_')
      printf '            %s,\n' "$constant"
    done < "$temporary/sorted-opcodes-$namespace"
    printf '        ];\n    }\n'
  done
  printf '}\n'
  printf '\npub const OPCODES: &[(&str, &[&[u8]])] = &[\n'
  for namespace in "${namespaces[@]}"; do
    printf '    ("%s", opcode::%s::ALL),\n' "$namespace" "$namespace"
  done
  printf '];\n'
  printf '\npub fn target() -> Option<&\047static str> {\n'
  printf '    #[cfg(all(target_arch = "x86_64", target_os = "linux"))]\n    {\n        Some("x86_64-linux")\n    }\n'
  printf '    #[cfg(all(target_arch = "aarch64", target_os = "linux"))]\n    {\n        Some("aarch64-linux")\n    }\n'
  printf '    #[cfg(all(target_arch = "aarch64", target_os = "macos"))]\n    {\n        Some("aarch64-darwin")\n    }\n'
  printf '    #[cfg(not(any(\n        all(target_arch = "x86_64", target_os = "linux"),\n        all(target_arch = "aarch64", target_os = "linux"),\n        all(target_arch = "aarch64", target_os = "macos")\n    )))]\n    {\n        None\n    }\n}\n'
  printf '\npub fn description() -> Option<String> {\n'
  printf '    target()\n        .map(|target| format!("monk-runtime {ABI} {PROFILE}\\n{CAPABILITIES}\\ntarget {target}\\n"))\n}\n'
} > "$temporary/abi2.rs"

if [[ $mode == check ]]; then
  cmp "$temporary/Abi2.hs" "$haskell_file"
  cmp "$temporary/abi2.rs" "$rust_file"
else
  cp "$temporary/Abi2.hs" "$haskell_file"
  cp "$temporary/abi2.rs" "$rust_file"
fi
